services:
  - type: web
    name: excel-transformer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: POSTAL_CODE_MASTER_FILE
        value: ../data/postal_code_master.xlsx
    healthCheckPath: /health